FROM alpine:3.3

MAINTAINER Data Conservancy <dc-ird@googlegroups.com>

ENV SHARED /shared

RUN apk update   && \
  apk add openrc && \
  apk add samba  && \
  apk add samba-common-tools && \
  apk add gettext

RUN apk upgrade samba-4.4.3 \
          --allow-untrusted \
          --update-cache    \
          --repository http://dl-3.alpinelinux.org/alpine/edge/main/ 

VOLUME ${SHARED}

RUN chown nobody:nobody ${SHARED} && \
    chmod 4775 ${SHARED}

ADD smb.conf ${SHARED}/etc/samba/smb.conf.tmpl

EXPOSE 137 138 139 445

ADD samba-entrypoint.sh /

RUN chmod 700 /samba-entrypoint.sh

ENTRYPOINT [ "/samba-entrypoint.sh" ]
